version: '3'
services:
    wp:
        image: wordpress
        ports:
            - "8080:80"
        environment:
            - WORDPRESS_DB_HOST=db
            - WORDPRESS_DB_USER=root
            - WORDPRESS_DB_PASSWORD=
            - WORDPRESS_DB_NAME=demoCron
            - WORDPRESS_TABLE_PREFIX=wp_
            - WORDPRESS_DEBUG=1
        depends_on:
            - db
            - mailhog
        volumes:
            - ./:/var/www/html/wp-content/plugins/wp_cron_tash_memo
    db:
        image: mysql:5
        ports:
            - "3307:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_USER: 'root'
        volumes:
            - .docker/data/mysqlSf:/var/lib/mysql

    mailhog:
        image: mailhog/mailhog:v1.0.0
        ports:
            - "1025:1025"
            - "8025:8025"